<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{meta.title}}</title>
    <meta name="description" content="{{meta.description}}">
    <meta name="keywords" content="{{meta.keywords}}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

	<meta name="twitter:title" content="{{meta.title}}">
	<meta name="twitter:description" content="{{meta.description}}">

	<meta name="twitter:site" content="@mxbrry">
	<meta name="twitter:site:id" content="276204106">
	<meta name="twitter:creator" content="@mxbrry">
	<meta name="twitter:creator:id" content="276204106">

	<meta name="twitter:url" content="http://textshadow.demo.mxbry.com/">
	<meta name="twitter:domain" content="http://textshadow.demo.mxbry.com/">
	<meta name="twitter:card" content="summary">

	<meta name="twitter:image:src" content="http://textshadow.demo.mxbry.com/img/social.png">
	<meta name="twitter:image:width" content="1000">
	<meta name="twitter:image:height" content="1000">

	<meta property="og:title" content="{{meta.title}}">
	<meta property="og:description" content="{{meta.description}}">
	<meta property="og:url" content="http://textshadow.demo.mxbry.com/">
	<meta property="og:site_name" content="Text Shadow Experiments | mxbry.com">
	<meta property="og:image" content="http://textshadow.demo.mxbry.com/img/social.fb.png">
	<meta property="og:type" content="website">
	<meta property="og:locale" content="en_US">
	<meta property="og:see_also" content="http://mxbry.com/">

    <link rel="stylesheet" href="/css/app.css">
    <link rel="stylesheet" href="/css/fonts.css">

    
    <script src="/js/modernizr.min.js"></script>
    

</head>

<body>
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-T3NDVH"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-T3NDVH');</script>
<!-- End Google Tag Manager -->
{{>body}}
<script src="/js/app.js"></script>
</body>

</html>
